title:              AlAgius blog
email:              agiusalexandre@gmail.com
description:        It Architect Blog
author:             Ale Agius
baseurl:            "/"
url:                "https://alagius.com"

# Social Profiles
twitter_username:   alex
github_username:    agiusalexandre
facebook_username:  agiusalexandre
linkedin_username:  agiusalexandre

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-152686626-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
